# Generated by Django 4.2.1 on 2023-05-19 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='organizers',
            field=models.ManyToManyField(related_name='organized_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='weather',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='organizers',
            field=models.ManyToManyField(related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='weather',
            field=models.TextField(blank=True),
        ),
    ]
