# Generated by Django 4.2.1 on 2023-05-19 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='activities',
            name='aend',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='activities',
            name='astart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='eend',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='estart',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
