# Generated by Django 4.2.1 on 2023-05-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
