# Generated by Django 4.2.1 on 2023-05-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_activities_budget_activities_description_and_more'),
        ('event', '0002_activities_date_alter_activities_aend_and_more'),
    ]

    operations = [
    ]
