# Generated by Django 4.2.1 on 2023-05-19 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_merge_20230519_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='aend',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='astart',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mainevent',
            name='eend',
        ),
        migrations.RemoveField(
            model_name='mainevent',
            name='estart',
        ),
        migrations.AddField(
            model_name='mainevent',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
