# Generated by Django 4.2.1 on 2023-05-19 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_aend_activities_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activities',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
