# Generated by Django 4.2.1 on 2023-05-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
