# Generated by Django 4.2.1 on 2023-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_activities_end_alter_activities_start_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainEvent',
            new_name='Event',
        ),
    ]
