# Generated by Django 4.2.1 on 2023-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_activity_organizers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.TextField(default='Nil'),
        ),
        migrations.AddField(
            model_name='event',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
