# Generated by Django 4.2.1 on 2023-07-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_message_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weather',
        ),
    ]
